name: flutter_hot_updates_workspace
publish_to: none

environment:
  sdk: ^3.12.2

workspace:
  - packages/flutter_hot_updates
  - packages/flutter_hot_updates_cli
  - examples/basic_flutter_app

dev_dependencies:
  melos: ^8.3.0

melos:
  scripts:
    analyze:
      run: dart run melos exec -- "flutter analyze ."
    test:
      run: dart run melos exec --dir-exists=test -- "flutter test"
    format:
      run: dart run melos exec -- "dart format ."
