name: flutter_hot_updates_cli
description: Command-line tooling for flutter_hot_updates releases and patches.
version: 0.0.1
homepage: https://github.com/flutter-hot-updates/flutter_hot_updates
repository: https://github.com/flutter-hot-updates/flutter_hot_updates
issue_tracker: https://github.com/flutter-hot-updates/flutter_hot_updates/issues

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  args: ^2.6.0
  archive: ^4.0.7
  asn1lib: ^1.6.5
  crypto: ^3.0.0
  http: ^1.2.0
  pointycastle: ^4.0.0
  yaml: ^3.1.2

executables:
  hot_updates:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
